using System;
using System.Collections.Generic;

namespace Sicem_Blazor.Models.Entities.Arquos
{
    public partial class VwCatPadron
    {
        public decimal IdPadron { get; set; }
        public decimal IdCuenta { get; set; }
        public string RazonSocial { get; set; }
        public string NomComercial { get; set; }
        public string NomPropietario { get; set; }
        public string Rfc { get; set; }
        public string Direccion { get; set; }
        public string Colonia { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string CodigoPostal { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Telefono3 { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string Extension3 { get; set; }
        public string TelefonoFax { get; set; }
        public string Email { get; set; }
        public string PaginaInternet { get; set; }
        public string CallePpal { get; set; }
        public string NumExt { get; set; }
        public string NumInt { get; set; }
        public string CalleLat1 { get; set; }
        public string CalleLat2 { get; set; }
        public decimal? Ruta { get; set; }
        public string Localizacion { get; set; }
        public decimal? AreaLote { get; set; }
        public decimal? AreaJardin { get; set; }
        public decimal? Viviendas { get; set; }
        public decimal? Frente { get; set; }
        public DateTime? FechaAlta { get; set; }
        public string NombreJubilado { get; set; }
        public decimal? Dependen { get; set; }
        public DateTime? FechaNacimiento { get; set; }
        public string DocumentoNo { get; set; }
        public string NombreEmpresa { get; set; }
        public string ObservaJubilado { get; set; }
        public string CveRegjubilado { get; set; }
        public decimal? PromedioAnt { get; set; }
        public decimal? PromedioAct { get; set; }
        public decimal? MesAdeudoAnt { get; set; }
        public decimal? MesAdeudoAct { get; set; }
        public decimal? ConsumoFijo { get; set; }
        public decimal? ImporteFijo { get; set; }
        public decimal? ImporteFijoDren { get; set; }
        public decimal? ImporteFijoSane { get; set; }
        public decimal? LecturaAnt { get; set; }
        public decimal? LecturaAct { get; set; }
        public decimal? ConsumoAnt { get; set; }
        public decimal? ConsumoAct { get; set; }
        public decimal? Subtotal { get; set; }
        public decimal? Iva { get; set; }
        public decimal? Total { get; set; }
        public decimal? ConsumoForzado { get; set; }
        public bool? EsFiscal { get; set; }
        public decimal? PorDescto { get; set; }
        public bool? Visitar { get; set; }
        public decimal? Desviacion { get; set; }
        public decimal? Longitud { get; set; }
        public decimal? Latitud { get; set; }
        public string Colonia1 { get; set; }
        public string Poblacion { get; set; }
        public string Estatus { get; set; }
        public string Calculo { get; set; }
        public string Servicio { get; set; }
        public string Tipousuario { get; set; }
        public string Tarifafija { get; set; }
        public string Claseusuario { get; set; }
        public string Tipogrupo { get; set; }
        public string Giro { get; set; }
        public string Situacion { get; set; }
        public string AnomaliaAct { get; set; }
        public string AnomaliaAnt { get; set; }
        public string Diametro { get; set; }
        public string Hidrocircuito { get; set; }
        public string CallePpal1 { get; set; }
        public string CalleLat11 { get; set; }
        public string CalleLat21 { get; set; }
        public string Materialmedidor { get; set; }
        public string Tipoinstalacion { get; set; }
        public string Ubicacionmedidor { get; set; }
        public string AlculoAct { get; set; }
        public string CalculoAnt { get; set; }
        public string Edocivil { get; set; }
        public string Tipojubilado { get; set; }
        public string Tipodocto { get; set; }
        public string Tipocasa { get; set; }
        public string Tipoempresa { get; set; }
        public string Tipotoma { get; set; }
        public string MaterialToma { get; set; }
        public string MaterialCalle { get; set; }
        public string MaterialBanqueta { get; set; }
        public string Tipotuberia { get; set; }
        public string Tipofactible { get; set; }
        public string MesFacturado { get; set; }
        public string FechaAlta1 { get; set; }
        public string FechaNacimiento1 { get; set; }
        public int? Edad { get; set; }
        public string JubiladoIngreso { get; set; }
        public string AltaFactura { get; set; }
        public string FechaLecturaAnt { get; set; }
        public string FechaLecturaAct { get; set; }
        public string FechaFacturaAnt { get; set; }
        public string FechaFacturaAct { get; set; }
        public string FechaVencimiento { get; set; }
        public string FechaInsert { get; set; }
    }
}
