# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish and Release

on:
  push:
    tags:
      - 'v*'  # Runs only when a tag like "v1.0.0" is pushed
    branches:
    - "main"
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build and Upload Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Blazor App
        run: dotnet build --configuration Release --no-restore

      - name: Publish Blazor App
        run: dotnet publish -c Release -o ./publish

      - name: Upload Published App as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SicemCaev-app
          path: ./publish
          retention-days: 7  # Store for 7 days

  release:
    name: Create GitHub Release
    needs: build  # Waits for the build job to finish
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: SicemCaev-app
          path: ./release-files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}  # Uses the pushed tag (e.g., v1.0.0)
          name: Release ${{ github.ref_name }}
          body: "Automated release of Blazor app."
          draft: false
          prerelease: false
          files: ./release-files/**  # Attach all published files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
